// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW-HDmxQsixuYN7yA4MGQNy4iFOFSrAGA',
    appId: '1:578527865407:web:d3117b0bf963b3016e668a',
    messagingSenderId: '578527865407',
    projectId: 'note-e00a2',
    authDomain: 'note-e00a2.firebaseapp.com',
    storageBucket: 'note-e00a2.firebasestorage.app',
    measurementId: 'G-NDHD4BF2DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykY4F8k58oYyibA3_lmSuDK-24jRJ6Oc',
    appId: '1:578527865407:android:aefa883f95ea19336e668a',
    messagingSenderId: '578527865407',
    projectId: 'note-e00a2',
    storageBucket: 'note-e00a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZSHc9y7Tlw_JJU0mTvG_sHEiW3-OtH0',
    appId: '1:578527865407:ios:f5347232000fe9b06e668a',
    messagingSenderId: '578527865407',
    projectId: 'note-e00a2',
    storageBucket: 'note-e00a2.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZSHc9y7Tlw_JJU0mTvG_sHEiW3-OtH0',
    appId: '1:578527865407:ios:f5347232000fe9b06e668a',
    messagingSenderId: '578527865407',
    projectId: 'note-e00a2',
    storageBucket: 'note-e00a2.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW-HDmxQsixuYN7yA4MGQNy4iFOFSrAGA',
    appId: '1:578527865407:web:e129c258df608cbb6e668a',
    messagingSenderId: '578527865407',
    projectId: 'note-e00a2',
    authDomain: 'note-e00a2.firebaseapp.com',
    storageBucket: 'note-e00a2.firebasestorage.app',
    measurementId: 'G-GGNB7K4TTX',
  );
}
